services:
  softon-portal-postgres:
    image: postgres:17
    container_name: softon-portal-postgres
    environment:
      POSTGRES_DB: softon_intranet
      POSTGRES_USER: softon_intranet
      POSTGRES_PASSWORD: 'softon!@#'
    ports:
      - "5432:5432"
    volumes:
      - softon-portal-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U softon_intranet -d softon_intranet"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  softon-portal-postgres:
