-- DocFlow — seed templates de página (20 modelos + versões)

INSERT INTO public.tb_pagina_template (id, codigo, nome, descricao, conteudo_html, ordem, ativo, created_at, updated_at, created_by, updated_by, personalizado, projeto_id, cliente_id, versao_atual) VALUES
	('10000000-0000-0000-0000-000000000001', 'FUNCIONALIDADE', 'Guia de funcionalidade', 'Apresenta objetivo, visão da tela e pontos. Grades com --1 (tela toda), --2 (meia) ou --3 (3 colunas).', '
<section class="doc-intro"><span class="doc-kicker">Guia da funcionalidade</span><h2>Visão geral da funcionalidade</h2><p>Apresente em uma frase o que o recurso permite fazer e para quem ele foi criado.</p></section>
<div class="objective-card"><p><strong>Objetivo desta funcionalidade</strong></p><p>Explique o ganho para o usuário e o resultado de negócio esperado.</p></div>
<section class="doc-section"><h2>Visão da tela</h2><p>Use esta área para orientar visualmente os principais pontos da interface.</p><figure class="screen-frame"><div class="screen-placeholder"><strong>Insira aqui uma captura da tela</strong><span>Use a ferramenta de imagem do editor e substitua este bloco.</span></div><figcaption>Tela principal da funcionalidade.</figcaption></figure></section>
<div class="callout"><strong>Layout da grade</strong><p>Altere a classe: <code>annotation-grid--1</code> tela toda · <code>annotation-grid--2</code> meia tela · <code>annotation-grid--3</code> três colunas.</p></div>
<section class="doc-section"><h2>Principais elementos</h2><div class="annotation-grid annotation-grid--3"><article class="annotation-card"><h3>Acesso principal</h3><p>Indique onde o usuário inicia a operação.</p></article><article class="annotation-card"><h3>Área de trabalho</h3><p>Explique onde os dados são exibidos ou preenchidos.</p></article><article class="annotation-card"><h3>Ação de confirmação</h3><p>Mostre como concluir e salvar a operação.</p></article></div></section>
<section class="doc-section"><h2>Regras e orientações</h2><div class="content-grid content-grid--2"><article class="rule-card"><h3>Regra de negócio</h3><p>Descreva uma validação importante e seu impacto.</p></article><article class="rule-card"><h3>Boa prática</h3><p>Registre uma recomendação que evite erros recorrentes.</p></article></div></section>
<div class="result-card"><strong>Resultado esperado</strong><p>Informe o que será apresentado após a conclusão bem-sucedida.</p></div>
', 10, true, '2026-08-03 01:37:36.839875+00', '2026-08-03 01:37:37.029973+00', 'migration', 'migration', false, NULL, NULL, 1),
	('10000000-0000-0000-0000-000000000002', 'PASSO_A_PASSO', 'Passo a passo visual', 'Guia operacional com preparação, fluxo horizontal, etapas e validação final.', '
<section class="doc-intro"><span class="doc-kicker">Guia operacional</span><h2>Como realizar o procedimento</h2><p>Resuma o procedimento, quando ele deve ser executado e o tempo estimado.</p></section>
<div class="objective-card"><p><strong>Antes de começar</strong></p><p>Liste permissões, dados e condições necessárias para seguir este guia.</p></div>
<section class="doc-section"><h2>Fluxo do procedimento</h2><ol class="flow-strip"><li><strong>Acessar</strong><span>Abra a tela indicada.</span></li><li><strong>Preencher</strong><span>Informe os dados solicitados.</span></li><li><strong>Revisar</strong><span>Confira as informações.</span></li><li><strong>Concluir</strong><span>Confirme a operação.</span></li></ol></section>
<section class="doc-section"><h2>Passo a passo detalhado</h2><div class="screen-grid"><article class="guide-card"><span class="guide-card__number">1</span><div class="screen-placeholder screen-placeholder--compact"><strong>Captura da etapa 1</strong><span>Insira a imagem correspondente.</span></div><h3>Acesse a funcionalidade</h3><p>Indique o caminho de navegação e o ponto de entrada.</p></article><article class="guide-card"><span class="guide-card__number">2</span><div class="screen-placeholder screen-placeholder--compact"><strong>Captura da etapa 2</strong><span>Insira a imagem correspondente.</span></div><h3>Preencha e revise</h3><p>Explique os dados necessários e as validações da tela.</p></article><article class="guide-card"><span class="guide-card__number">3</span><div class="screen-placeholder screen-placeholder--compact"><strong>Captura da etapa 3</strong><span>Insira a imagem correspondente.</span></div><h3>Confirme a operação</h3><p>Mostre a ação final e a mensagem apresentada.</p></article></div></section>
<div class="result-card"><strong>Como validar</strong><p>Explique como confirmar visualmente que o procedimento funcionou.</p></div>
', 20, true, '2026-08-03 01:37:36.839875+00', '2026-08-03 01:37:36.890464+00', 'migration', 'migration', false, NULL, NULL, 1),
	('10000000-0000-0000-0000-000000000007', 'DICIONARIO_CAMPOS', 'Dicionário de campos', 'Catálogo visual de campos com obrigatoriedade, exemplo e impacto no negócio.', '
<section class="doc-intro"><span class="doc-kicker">Referência de dados</span><h2>Dicionário de campos — [tela]</h2><p>Documente o significado de cada campo e o impacto de um preenchimento incorreto.</p></section>
<div class="objective-card"><p><strong>Objetivo deste dicionário</strong></p><p>Padronizar o entendimento funcional e apoiar usuários, produto, suporte e desenvolvimento.</p></div>
<section class="doc-section"><h2>Visão da tela</h2><figure class="screen-frame"><div class="screen-placeholder"><strong>Insira a captura com os campos numerados</strong><span>Use os números da imagem na primeira coluna da tabela.</span></div><figcaption>Campos mapeados para o dicionário abaixo.</figcaption></figure></section>
<section class="doc-section"><h2>Descrição dos campos</h2><div class="table-wrap"><table class="dictionary-table"><thead><tr><th>#</th><th>Campo</th><th>Descrição</th><th>Obrigatório?</th><th>Exemplo</th><th>Impacto no negócio</th></tr></thead><tbody><tr><td><span class="number-badge">1</span></td><td><strong>Nome do campo</strong></td><td>Explique finalidade, formato e origem da informação.</td><td><span class="status-badge status-badge--required">Sim</span></td><td>Valor de exemplo</td><td>Descreva o efeito deste dado nos processos.</td></tr><tr><td><span class="number-badge">2</span></td><td><strong>Outro campo</strong></td><td>Detalhe regras, limites e dependências.</td><td><span class="status-badge">Não</span></td><td>Valor de exemplo</td><td>Informe relatórios, integrações ou decisões afetadas.</td></tr></tbody></table></div></section>
<section class="doc-section"><h2>Observações importantes</h2><div class="content-grid content-grid--3"><article class="rule-card"><h3>Validações</h3><p>Liste formatos e mensagens de erro.</p></article><article class="rule-card"><h3>Dependências</h3><p>Explique campos condicionais e relacionamentos.</p></article><article class="rule-card"><h3>Segurança</h3><p>Indique dados sensíveis e restrições de acesso.</p></article></div></section>
', 50, true, '2026-08-03 01:37:36.890464+00', '2026-08-03 01:37:36.890464+00', 'migration', 'migration', false, NULL, NULL, 1),
	('10000000-0000-0000-0000-000000000008', 'PROCESSO', 'Fluxo de processo', 'Documenta etapas, telas envolvidas, regras e resumo de um processo ponta a ponta.', '
<section class="doc-intro"><span class="doc-kicker">Processo ponta a ponta</span><h2>Processo de [nome do processo]</h2><p>Explique o início, o fim e os participantes deste fluxo.</p></section>
<div class="objective-card"><p><strong>Objetivo do processo</strong></p><p>Descreva o resultado de negócio, as áreas envolvidas e o tempo esperado.</p></div>
<section class="doc-section"><h2>Visão geral do fluxo</h2><ol class="flow-strip"><li><strong>Solicitação</strong><span>O processo é iniciado.</span></li><li><strong>Análise</strong><span>Os dados são validados.</span></li><li><strong>Aprovação</strong><span>O responsável decide.</span></li><li><strong>Conclusão</strong><span>O resultado é registrado.</span></li></ol></section>
<section class="doc-section"><h2>Telas envolvidas</h2><div class="screen-grid"><article class="guide-card"><span class="guide-card__number">1</span><div class="screen-placeholder screen-placeholder--compact"><strong>Tela de entrada</strong><span>Insira uma captura.</span></div><h3>Início do processo</h3><p>Explique como a solicitação é registrada.</p></article><article class="guide-card"><span class="guide-card__number">2</span><div class="screen-placeholder screen-placeholder--compact"><strong>Tela de análise</strong><span>Insira uma captura.</span></div><h3>Análise e decisão</h3><p>Mostre validações, responsáveis e ações.</p></article><article class="guide-card"><span class="guide-card__number">3</span><div class="screen-placeholder screen-placeholder--compact"><strong>Tela final</strong><span>Insira uma captura.</span></div><h3>Conclusão</h3><p>Descreva o retorno e os registros gerados.</p></article></div></section>
<section class="doc-section"><h2>Regras do processo</h2><div class="content-grid content-grid--3"><article class="rule-card"><h3>Entrada</h3><p>Informe critérios para iniciar o fluxo.</p></article><article class="rule-card"><h3>Decisão</h3><p>Registre aprovações, exceções e alçadas.</p></article><article class="rule-card"><h3>Saída</h3><p>Explique notificações e dados gerados.</p></article></div></section>
<section class="doc-section"><h2>Resumo das etapas</h2><div class="table-wrap"><table><thead><tr><th>Etapa</th><th>Responsável</th><th>Entrada</th><th>Saída</th></tr></thead><tbody><tr><td>Solicitação</td><td>Perfil ou área</td><td>Dados necessários</td><td>Registro criado</td></tr><tr><td>Análise</td><td>Perfil ou área</td><td>Registro pendente</td><td>Decisão registrada</td></tr></tbody></table></div></section>
', 60, true, '2026-08-03 01:37:36.890464+00', '2026-08-03 01:37:36.890464+00', 'migration', 'migration', false, NULL, NULL, 1),
	('10000000-0000-0000-0000-000000000004', 'CONSULTA', 'Consulta ou listagem', 'Explica filtros, listagem e ações. Use annotation-grid--1 (tela toda), --2 (meia tela) ou --3 (3 colunas).', '
<section class="doc-intro"><span class="doc-kicker">Consulta e listagem</span><h2>Consulta de [registros]</h2><p>Apresente as informações disponíveis e as situações em que esta consulta é útil.</p></section>
<div class="objective-card"><p><strong>Objetivo desta tela</strong></p><p>Explique quais decisões ou tarefas a consulta ajuda o usuário a realizar.</p></div>
<section class="doc-section"><h2>Visão da tela</h2><figure class="screen-frame"><div class="screen-placeholder"><strong>Insira a captura da consulta</strong><span>Deixe filtros, tabela e ações visíveis.</span></div><figcaption>Visão geral dos filtros e resultados.</figcaption></figure></section>
<div class="callout"><strong>Layout da grade</strong><p>Troque a classe da grade conforme o espaço desejado: <code>annotation-grid--1</code> (tela toda), <code>annotation-grid--2</code> (meia tela) ou <code>annotation-grid--3</code> (3 colunas). O mesmo vale para <code>content-grid--1</code>, <code>--2</code> e <code>--3</code>.</p></div>
<section class="doc-section"><h2>Elementos da tela</h2><div class="annotation-grid annotation-grid--3"><article class="annotation-card"><h3>Filtros</h3><p>Descreva os principais critérios de pesquisa.</p></article><article class="annotation-card"><h3>Pesquisar e limpar</h3><p>Explique o comportamento de cada ação.</p></article><article class="annotation-card"><h3>Resultados</h3><p>Apresente as colunas e a ordenação padrão.</p></article><article class="annotation-card"><h3>Ações por registro</h3><p>Detalhe visualizar, editar e excluir.</p></article></div></section>
<section class="doc-section"><div class="content-grid content-grid--2"><article class="rule-card"><h2>Regras de negócio</h2><ul><li>Informe limites e combinações de filtros.</li><li>Explique visibilidade e permissões.</li></ul></article><article class="rule-card"><h2>Exemplos de uso</h2><ul><li>Localizar registros por nome ou período.</li><li>Filtrar itens por situação.</li><li>Abrir os detalhes de um resultado.</li></ul></article></div></section>
', 40, true, '2026-08-03 01:37:36.839875+00', '2026-08-03 01:37:37.029973+00', 'migration', 'migration', false, NULL, NULL, 1),
	('10000000-0000-0000-0000-000000000005', 'FAQ', 'Perguntas frequentes', 'Organiza atalhos por assunto e dúvidas recorrentes em cartões objetivos.', '
<section class="doc-intro"><span class="doc-kicker">Central de dúvidas</span><h2>Perguntas frequentes</h2><p>Reúna respostas curtas e diretas para as dúvidas mais recorrentes.</p></section>
<section class="doc-section"><h2>Acesso rápido</h2><div class="content-grid content-grid--3"><article class="topic-card"><span class="topic-card__icon">01</span><h3>Primeiros passos</h3><p>Dúvidas sobre acesso e configuração inicial.</p></article><article class="topic-card"><span class="topic-card__icon">02</span><h3>Operação</h3><p>Orientações para as tarefas do dia a dia.</p></article><article class="topic-card"><span class="topic-card__icon">03</span><h3>Erros comuns</h3><p>Soluções rápidas para situações conhecidas.</p></article></div></section>
<section class="doc-section faq-list"><article class="faq-item"><h3>Quando devo utilizar esta funcionalidade?</h3><p>Responda objetivamente e indique o cenário recomendado.</p></article><article class="faq-item"><h3>O que fazer quando a operação não for concluída?</h3><p>Indique verificações iniciais e quando acionar o suporte.</p></article><article class="faq-item"><h3>Posso desfazer esta ação?</h3><p>Explique se a operação é reversível e quais cuidados tomar.</p></article></section>
', 70, true, '2026-08-03 01:37:36.839875+00', '2026-08-03 01:37:36.890464+00', 'migration', 'migration', false, NULL, NULL, 1),
	('10000000-0000-0000-0000-000000000006', 'SOLUCAO_PROBLEMAS', 'Solução de problemas', 'Relaciona sintomas, causas, diagnóstico visual e ações corretivas.', '
<section class="doc-intro"><span class="doc-kicker">Diagnóstico e solução</span><h2>Problema: [sintoma principal]</h2><p>Descreva a mensagem, o comportamento observado e em qual etapa ocorre.</p></section>
<div class="objective-card"><p><strong>Antes de investigar</strong></p><p>Registre versão, usuário, horário e evidências necessárias para reproduzir o problema.</p></div>
<section class="doc-section"><div class="content-grid content-grid--2"><article class="rule-card"><h2>Sintomas</h2><ul><li>Mensagem apresentada.</li><li>Comportamento inesperado.</li><li>Condição em que acontece.</li></ul></article><article class="rule-card"><h2>Possíveis causas</h2><ul><li>Permissão ou configuração.</li><li>Dado inválido ou incompleto.</li><li>Indisponibilidade de integração.</li></ul></article></div></section>
<section class="doc-section"><h2>Como resolver</h2><ol class="flow-strip"><li><strong>Verificar</strong><span>Confirme dados e acessos.</span></li><li><strong>Corrigir</strong><span>Aplique a orientação.</span></li><li><strong>Testar</strong><span>Repita a operação.</span></li><li><strong>Registrar</strong><span>Documente o resultado.</span></li></ol></section>
<section class="doc-section"><h2>Evidência visual</h2><figure class="screen-frame"><div class="screen-placeholder"><strong>Insira a captura da mensagem ou comportamento</strong><span>Oculte dados pessoais e destaque a área relevante.</span></div><figcaption>Exemplo do problema e do ponto que deve ser verificado.</figcaption></figure></section>
<div class="warning"><strong>Quando acionar o suporte</strong><p>Informe os critérios de escalonamento e quais evidências devem ser enviadas.</p></div>
', 80, true, '2026-08-03 01:37:36.839875+00', '2026-08-03 01:37:36.890464+00', 'migration', 'migration', false, NULL, NULL, 1),
	('10000000-0000-0000-0000-000000000009', 'CENTRAL_AJUDA', 'Central de ajuda', 'Página inicial com acessos rápidos, destaques, tipos de documentação e conteúdo recente.', '
<section class="doc-intro doc-intro--center"><span class="doc-kicker">Portal de conhecimento</span><h2>Central de ajuda [produto]</h2><p>Apresente o propósito da central e ajude o usuário a encontrar rapidamente o conteúdo certo.</p></section>
<section class="doc-section"><h2>Acesso rápido</h2><div class="content-grid content-grid--3"><article class="topic-card"><span class="topic-card__icon">01</span><h3>Primeiros passos</h3><p>Conceitos essenciais para começar com segurança.</p></article><article class="topic-card"><span class="topic-card__icon">02</span><h3>Cadastros</h3><p>Orientações para criar e manter informações.</p></article><article class="topic-card"><span class="topic-card__icon">03</span><h3>Operações</h3><p>Fluxos e procedimentos das rotinas principais.</p></article><article class="topic-card"><span class="topic-card__icon">04</span><h3>Relatórios</h3><p>Consultas, indicadores e exportações.</p></article><article class="topic-card"><span class="topic-card__icon">05</span><h3>Configurações</h3><p>Personalização, acessos e regras do sistema.</p></article><article class="topic-card"><span class="topic-card__icon">06</span><h3>Financeiro</h3><p>Contas, títulos, recebimentos e pagamentos.</p></article></div></section>
<section class="doc-section"><h2>Guias em destaque</h2><div class="screen-grid"><article class="guide-card"><span class="guide-card__number">1</span><div class="screen-placeholder screen-placeholder--compact"><strong>Imagem do guia</strong><span>Insira uma captura de destaque.</span></div><h3>Guia visual em destaque</h3><p>Resuma o resultado que o usuário alcançará.</p></article><article class="guide-card"><span class="guide-card__number">2</span><div class="screen-placeholder screen-placeholder--compact"><strong>Imagem do guia</strong><span>Insira uma captura de destaque.</span></div><h3>Procedimento recomendado</h3><p>Apresente uma rotina importante do sistema.</p></article><article class="guide-card"><span class="guide-card__number">3</span><div class="screen-placeholder screen-placeholder--compact"><strong>Imagem do guia</strong><span>Insira uma captura de destaque.</span></div><h3>Relatório mais acessado</h3><p>Mostre como transformar dados em decisão.</p></article></div></section>
<section class="doc-section"><div class="content-grid content-grid--2"><article class="rule-card"><h2>Artigos recentes</h2><div class="resource-list"><div class="resource-item"><strong>Nome do artigo publicado</strong><span>Atualizado recentemente</span></div><div class="resource-item"><strong>Outro conteúdo importante</strong><span>Categoria do artigo</span></div><div class="resource-item"><strong>Boas práticas para usuários</strong><span>Tempo de leitura</span></div></div></article><article class="rule-card"><h2>Perguntas frequentes</h2><div class="faq-list"><article class="faq-item"><h3>Como encontro uma funcionalidade?</h3><p>Oriente o uso da busca e das categorias.</p></article><article class="faq-item"><h3>Onde solicito ajuda?</h3><p>Indique os canais disponíveis.</p></article></div></article></div></section>
', 5, true, '2026-08-03 01:37:36.905124+00', '2026-08-03 01:37:36.905124+00', 'migration', 'migration', false, NULL, NULL, 1),
	('10000000-0000-0000-0000-000000000010', 'CATEGORIA_ARTIGOS', 'Índice de categoria', 'Organiza artigos por assunto com filtros, metadados, conteúdos populares e tutoriais.', '
<section class="doc-intro"><span class="doc-kicker">Módulo ou categoria</span><h2>[Nome da categoria]</h2><p>Explique quais temas e atividades o usuário encontrará nesta seção.</p></section>
<div class="filter-chips"><p><span class="filter-chip filter-chip--active">Todos</span><span class="filter-chip">Assunto 1</span><span class="filter-chip">Assunto 2</span><span class="filter-chip">Importação e exportação</span><span class="filter-chip">Permissões</span></p></div>
<section class="doc-section"><h2>Guias disponíveis</h2><div class="resource-list resource-list--large"><article class="resource-item"><span class="number-badge">1</span><span><strong>Como realizar a atividade principal</strong><small>Explique o objetivo deste artigo em uma frase.</small></span><span class="resource-item__meta">6 min · atualizado recentemente</span></article><article class="resource-item"><span class="number-badge">2</span><span><strong>Como configurar uma opção</strong><small>Apresente o resultado esperado do guia.</small></span><span class="resource-item__meta">7 min · guia visual</span></article><article class="resource-item"><span class="number-badge">3</span><span><strong>Importação de informações</strong><small>Oriente sobre formatos, regras e validações.</small></span><span class="resource-item__meta">9 min · passo a passo</span></article><article class="resource-item"><span class="number-badge">4</span><span><strong>Exportação de informações</strong><small>Mostre como gerar e utilizar o arquivo.</small></span><span class="resource-item__meta">6 min · referência</span></article></div></section>
<section class="doc-section"><div class="content-grid content-grid--2"><article class="rule-card"><h2>Artigos populares</h2><ol class="rank-list"><li>Conteúdo mais acessado da categoria</li><li>Dúvida recorrente dos usuários</li><li>Boas práticas recomendadas</li><li>Solução para um erro conhecido</li></ol></article><article class="rule-card"><h2>Tutoriais relacionados</h2><div class="content-grid content-grid--2"><article class="topic-card"><span class="topic-card__icon">▶</span><h3>Tutorial visual</h3><p>Inclua duração e benefício.</p></article><article class="topic-card"><span class="topic-card__icon">▶</span><h3>Demonstração prática</h3><p>Explique o que será demonstrado.</p></article></div></article></div></section>
', 65, true, '2026-08-03 01:37:36.905124+00', '2026-08-03 01:37:36.905124+00', 'migration', 'migration', false, NULL, NULL, 1),
	('10000000-0000-0000-0000-000000000011', 'PRIMEIROS_PASSOS', 'Primeiros passos', 'Jornada inicial com etapas, tutoriais, checklist de implantação e materiais complementares.', '
<section class="doc-intro"><span class="doc-kicker">Boas-vindas</span><h2>Primeiros passos no [produto]</h2><p>Apresente a jornada inicial para que o usuário comece com confiança.</p></section>
<section class="doc-section"><h2>Jornada inicial</h2><div class="journey-grid"><article class="journey-card"><span class="journey-card__number">1</span><h3>Acesso ao sistema</h3><p>Explique como entrar e navegar pela primeira vez.</p></article><article class="journey-card"><span class="journey-card__number">2</span><h3>Segurança inicial</h3><p>Oriente senha, autenticação e proteção da conta.</p></article><article class="journey-card"><span class="journey-card__number">3</span><h3>Configurar perfil</h3><p>Mostre preferências e informações pessoais.</p></article><article class="journey-card"><span class="journey-card__number">4</span><h3>Criar primeiro cadastro</h3><p>Ajude o usuário a registrar a primeira informação.</p></article><article class="journey-card"><span class="journey-card__number">5</span><h3>Consultar resultados</h3><p>Apresente consultas e relatórios essenciais.</p></article></div></section>
<section class="doc-section"><h2>Tutoriais visuais</h2><div class="screen-grid"><article class="guide-card"><div class="screen-placeholder screen-placeholder--compact"><strong>Imagem do tutorial</strong><span>Insira a captura da etapa.</span></div><h3>Como acessar o sistema</h3><p>Informe duração e aprendizado.</p></article><article class="guide-card"><div class="screen-placeholder screen-placeholder--compact"><strong>Imagem do tutorial</strong><span>Insira a captura da etapa.</span></div><h3>Configurando seu perfil</h3><p>Mostre o resultado do tutorial.</p></article><article class="guide-card"><div class="screen-placeholder screen-placeholder--compact"><strong>Imagem do tutorial</strong><span>Insira a captura da etapa.</span></div><h3>Visão geral de relatórios</h3><p>Apresente os principais indicadores.</p></article></div></section>
<section class="doc-section"><div class="content-grid content-grid--2"><article class="rule-card"><h2>Checklist de implantação</h2><ul class="status-list"><li class="status-item status-item--done"><span>Acessar com usuário administrador</span><strong>Concluído</strong></li><li class="status-item status-item--done"><span>Configurar perfil e preferências</span><strong>Concluído</strong></li><li class="status-item status-item--progress"><span>Criar primeiro cadastro</span><strong>Em andamento</strong></li><li class="status-item"><span>Consultar ou gerar um relatório</span><strong>Pendente</strong></li></ul></article><article class="rule-card"><h2>Materiais complementares</h2><div class="content-grid content-grid--3"><article class="topic-card"><span class="topic-card__icon">?</span><h3>FAQ</h3><p>Dúvidas comuns.</p></article><article class="topic-card"><span class="topic-card__icon">▶</span><h3>Vídeos</h3><p>Tutoriais rápidos.</p></article><article class="topic-card"><span class="topic-card__icon">A–Z</span><h3>Glossário</h3><p>Termos do sistema.</p></article></div></article></div></section>
', 68, true, '2026-08-03 01:37:36.905124+00', '2026-08-03 01:37:36.905124+00', 'migration', 'migration', false, NULL, NULL, 1),
	('10000000-0000-0000-0000-000000000012', 'RELATORIO', 'Guia de relatório', 'Documenta filtros, período, agrupamento, gráfico, tabela, exportação e boas práticas.', '
<section class="doc-intro"><span class="doc-kicker">Relatórios e indicadores</span><h2>Como gerar o relatório de [assunto]</h2><p>Explique como analisar dados, acompanhar indicadores e apoiar decisões.</p></section>
<div class="objective-card"><p><strong>Objetivo de negócio</strong></p><p>Descreva quais decisões este relatório apoia e quais resultados devem ser acompanhados.</p></div>
<section class="doc-section"><h2>Visão do relatório</h2><figure class="screen-frame"><div class="screen-placeholder"><strong>Insira a captura completa do relatório</strong><span>Mostre filtros, gráfico, tabela e ação de exportação.</span></div><figcaption>Visão geral do relatório e seus principais componentes.</figcaption></figure></section>
<section class="doc-section"><h2>Elementos da tela</h2><div class="annotation-grid"><article class="annotation-card"><h3>Filtros</h3><p>Liste os critérios e a forma como são combinados.</p></article><article class="annotation-card"><h3>Período</h3><p>Explique datas disponíveis e valores padrão.</p></article><article class="annotation-card"><h3>Agrupamento</h3><p>Descreva dia, semana, mês ou outra dimensão.</p></article><article class="annotation-card"><h3>Gráfico</h3><p>Oriente a leitura das séries e indicadores.</p></article><article class="annotation-card"><h3>Tabela</h3><p>Explique colunas, totais e detalhamento.</p></article><article class="annotation-card"><h3>Exportação</h3><p>Informe formatos e cuidados com os dados.</p></article></div></section>
<section class="doc-section"><div class="content-grid content-grid--2"><article class="rule-card"><h2>Regras de negócio</h2><ul class="checklist"><li>Explique como filtros são aplicados.</li><li>Informe as permissões necessárias.</li><li>Registre limites de período ou volume.</li></ul></article><article class="rule-card"><h2>Boas práticas</h2><div class="content-grid content-grid--2"><article class="topic-card"><h3>Defina o objetivo</h3><p>Saiba o que precisa analisar.</p></article><article class="topic-card"><h3>Compare períodos</h3><p>Identifique padrões e tendências.</p></article><article class="topic-card"><h3>Use filtros com critério</h3><p>Reduza ruído nos resultados.</p></article><article class="topic-card"><h3>Exporte e compartilhe</h3><p>Apoie decisões em equipe.</p></article></div></article></div></section>
<div class="related-links"><p><strong>Guias relacionados</strong><span>Personalizar colunas</span><span>Agendar relatório</span><span>Exportar dados</span></p></div>
', 45, true, '2026-08-03 01:37:36.905124+00', '2026-08-03 01:37:36.905124+00', 'migration', 'migration', false, NULL, NULL, 1),
	('10000000-0000-0000-0000-000000000018', 'INCLUIR_REGISTRO', 'Incluir registro', 'Guia de inclusão com pré-requisitos, imagem da tela, descrição de campos e validação final.', '
<section class="doc-intro"><span class="doc-kicker">Operação · Inclusão</span><h2>Como incluir [nome do registro]</h2><p>Explique qual informação será cadastrada, quem pode realizar a operação e onde ela será usada.</p></section>
<div class="objective-card"><p><strong>Antes de começar</strong></p><p>Informe permissões, dados obrigatórios e dependências necessárias para criar o registro.</p></div>
<section class="doc-section"><h2>Visão da tela</h2><figure class="screen-frame"><div class="screen-placeholder"><strong>Insira a captura da tela de inclusão</strong><span>Mostre os campos obrigatórios e o botão para salvar.</span></div><figcaption>Tela usada para incluir um novo registro.</figcaption></figure></section>
<section class="doc-section"><h2>Descrição dos campos</h2><div class="table-wrap"><table><thead><tr><th>Campo</th><th>Obrigatório</th><th>Como preencher</th><th>Exemplo</th></tr></thead><tbody><tr><td>Campo principal</td><td>Sim</td><td>Descreva formato, limite e regra de preenchimento.</td><td>Exemplo válido</td></tr><tr><td>Campo complementar</td><td>Não</td><td>Explique quando deve ser informado.</td><td>Exemplo</td></tr><tr><td>Status ou opção</td><td>Conforme regra</td><td>Descreva os valores disponíveis e seu efeito.</td><td>Ativo</td></tr></tbody></table></div></section>
<section class="doc-section"><h2>Passo a passo</h2><ol><li>Acesse o menu e selecione <strong>Novo</strong>.</li><li>Preencha os campos obrigatórios.</li><li>Revise as informações e selecione <strong>Salvar</strong>.</li><li>Confirme a mensagem de sucesso e localize o registro na lista.</li></ol></section>
<div class="result-card"><strong>Resultado esperado</strong><p>Descreva como confirmar que o registro foi incluído corretamente.</p></div>
', 95, true, '2026-08-03 01:37:37.002543+00', '2026-08-03 01:37:37.002543+00', 'migration', 'migration', false, NULL, NULL, 1),
	('10000000-0000-0000-0000-000000000019', 'EDITAR_REGISTRO', 'Editar registro', 'Guia de alteração com imagem da tela, campos editáveis, restrições e confirmação.', '
<section class="doc-intro"><span class="doc-kicker">Operação · Edição</span><h2>Como editar [nome do registro]</h2><p>Explique quando um registro deve ser alterado e quais dados não podem ser modificados.</p></section>
<section class="doc-section"><h2>Visão da tela</h2><figure class="screen-frame"><div class="screen-placeholder"><strong>Insira a captura da tela de edição</strong><span>Destaque dados atuais, campos editáveis e a ação de salvar.</span></div><figcaption>Tela de edição do registro.</figcaption></figure></section>
<section class="doc-section"><h2>Campos e regras de alteração</h2><div class="table-wrap"><table><thead><tr><th>Campo</th><th>Pode editar?</th><th>Regra</th><th>Impacto</th></tr></thead><tbody><tr><td>Identificação</td><td>Conforme regra</td><td>Informe se o valor é único ou bloqueado após a criação.</td><td>Explique o efeito nos registros relacionados.</td></tr><tr><td>Dados principais</td><td>Sim</td><td>Descreva validações e limites.</td><td>Atualiza a informação exibida no sistema.</td></tr><tr><td>Status</td><td>Conforme permissão</td><td>Explique transições permitidas.</td><td>Pode habilitar ou bloquear o uso do registro.</td></tr></tbody></table></div></section>
<section class="doc-section"><h2>Como editar</h2><ol class="flow-strip"><li><strong>Localizar</strong><span>Encontre o registro na lista.</span></li><li><strong>Abrir</strong><span>Selecione a ação de editar.</span></li><li><strong>Alterar</strong><span>Atualize apenas os campos necessários.</span></li><li><strong>Salvar</strong><span>Confirme a alteração.</span></li></ol></section>
<div class="warning"><strong>Atenção</strong><p>Descreva impactos, auditoria, permissões ou situações em que a alteração não deve ser feita.</p></div>
', 96, true, '2026-08-03 01:37:37.002543+00', '2026-08-03 01:37:37.002543+00', 'migration', 'migration', false, NULL, NULL, 1),
	('10000000-0000-0000-0000-000000000020', 'LISTAR_REGISTROS', 'Listar e consultar registros', 'Guia de consulta com imagem, filtros, descrição de colunas, ações e exportação.', '
<section class="doc-intro"><span class="doc-kicker">Operação · Consulta</span><h2>Como consultar [nome dos registros]</h2><p>Explique quais informações podem ser encontradas na lista e em quais cenários ela deve ser usada.</p></section>
<section class="doc-section"><h2>Visão da tela</h2><figure class="screen-frame"><div class="screen-placeholder"><strong>Insira a captura da tela de listagem</strong><span>Mostre filtros, tabela, paginação e ações disponíveis.</span></div><figcaption>Lista de registros e filtros de consulta.</figcaption></figure></section>
<section class="doc-section"><h2>Como pesquisar</h2><div class="content-grid content-grid--2"><article class="rule-card"><h3>Filtros</h3><p>Descreva cada filtro, combinações permitidas e valores padrão.</p></article><article class="rule-card"><h3>Ordenação e paginação</h3><p>Explique como ordenar resultados e navegar entre páginas.</p></article></div></section>
<section class="doc-section"><h2>Descrição das colunas</h2><div class="table-wrap"><table><thead><tr><th>Coluna</th><th>O que informa</th><th>Como interpretar</th></tr></thead><tbody><tr><td>Identificação</td><td>Código ou nome do registro.</td><td>Use para localizar o item correto.</td></tr><tr><td>Status</td><td>Situação atual do registro.</td><td>Explique os possíveis valores e cores.</td></tr><tr><td>Atualização</td><td>Data e responsável pela última alteração.</td><td>Use para conferir a vigência da informação.</td></tr><tr><td>Ações</td><td>Operações disponíveis na linha.</td><td>Detalhe visualizar, editar, excluir e exportar.</td></tr></tbody></table></div></section>
<section class="doc-section"><h2>Ações disponíveis</h2><div class="annotation-grid"><article class="annotation-card"><h3>Visualizar</h3><p>Explique o que pode ser consultado no detalhe.</p></article><article class="annotation-card"><h3>Editar</h3><p>Informe quem pode alterar e para onde a ação direciona.</p></article><article class="annotation-card"><h3>Exportar</h3><p>Descreva formato, filtros considerados e cuidados com os dados.</p></article></div></section>
', 97, true, '2026-08-03 01:37:37.002543+00', '2026-08-03 01:37:37.002543+00', 'migration', 'migration', false, NULL, NULL, 1),
	('10000000-0000-0000-0000-000000000003', 'CADASTRO', 'Cadastro ou edição', 'Documenta cadastro com captura e marcações. Layout da grade: content-grid/annotation-grid --1, --2 ou --3.', '
<section class="doc-intro"><span class="doc-kicker">Cadastro e edição</span><h2>Cadastro de [entidade]</h2><p>Explique quando este cadastro deve ser usado e o que será registrado.</p></section>
<div class="objective-card"><p><strong>Objetivo desta tela</strong></p><p>Descreva o valor do cadastro para a operação e quem pode realizá-lo.</p></div>
<section class="doc-section"><h2>Visão da tela</h2><figure class="screen-frame"><div class="screen-placeholder"><strong>Insira a captura da tela de cadastro</strong><span>Prefira uma imagem limpa, com os campos principais visíveis.</span></div><figcaption>Visão geral da tela de cadastro.</figcaption></figure></section>
<div class="callout"><strong>Layout da grade</strong><p>Use <code>annotation-grid--1</code> para ocupar a tela toda, <code>--2</code> para meia tela ou <code>--3</code> para três colunas.</p></div>
<section class="doc-section"><h2>Elementos da tela</h2><div class="annotation-grid annotation-grid--2"><article class="annotation-card"><h3>Campo principal</h3><p>Informe formato, limite e exemplo de preenchimento.</p></article><article class="annotation-card"><h3>Campos complementares</h3><p>Explique quando cada informação deve ser preenchida.</p></article><article class="annotation-card"><h3>Status ou opção</h3><p>Descreva o efeito de cada valor disponível.</p></article><article class="annotation-card"><h3>Ações</h3><p>Detalhe os botões Salvar, Cancelar e outras ações.</p></article></div></section>
<section class="doc-section"><div class="content-grid content-grid--2"><article class="rule-card"><h2>Regras de negócio</h2><ul class="checklist"><li>Registre uma validação obrigatória.</li><li>Explique duplicidade, limites ou dependências.</li></ul></article><article class="rule-card"><h2>Como cadastrar</h2><ol><li>Acesse a tela.</li><li>Preencha os campos indicados.</li><li>Revise e selecione <strong>Salvar</strong>.</li></ol></article></div></section>
<div class="callout"><strong>Artigos relacionados</strong><p>Inclua links para consulta, edição ou processos ligados a este cadastro.</p></div>
', 30, true, '2026-08-03 01:37:36.839875+00', '2026-08-03 01:37:37.029973+00', 'migration', 'migration', false, NULL, NULL, 1),
	('10000000-0000-0000-0000-000000000013', 'LAB_FILTROS', 'Laboratório de filtros', 'Critérios, combinações, triagem de resultados e ações recomendadas.', '
<section class="doc-intro"><span class="doc-kicker">Pesquisa com critérios</span><h2>Consultar [assunto]</h2><p>Documente a combinação de filtros, a leitura dos resultados e a decisão que cada item exige.</p></section>
<section class="doc-section"><h2>Cenários de uso</h2><div class="filter-chips"><p><span class="filter-chip filter-chip--active">Uso do dia</span><span class="filter-chip">Revisão periódica</span><span class="filter-chip">Busca pontual</span><span class="filter-chip">Retorno de tratamento</span></p></div></section>
<section class="doc-section"><h2>Receita de critérios</h2><div class="table-wrap"><table class="criteria-table"><thead><tr><th>Filtro</th><th>Quando usar</th><th>Exemplo</th><th>Combina com</th></tr></thead><tbody><tr><td><strong>Contexto / grupo</strong></td><td>Delimitar o escopo da consulta</td><td>Grupo ou fila de trabalho</td><td>Período, status</td></tr><tr><td><strong>Identificador</strong></td><td>Localizar um registro específico</td><td>Código, documento ou nome</td><td>Contexto</td></tr><tr><td><strong>Período</strong></td><td>Recortar a janela temporal</td><td>Últimos 7 dias</td><td>Status, categoria</td></tr><tr><td><strong>Status</strong></td><td>Separar pendentes de concluídos</td><td>Pendente</td><td>Contexto, responsável</td></tr></tbody></table></div></section>
<section class="doc-section"><h2>Triagem dos resultados</h2><div class="triage-board"><article class="triage-panel triage-panel--queue"><h3>Itens encontrados</h3><ul class="resource-list resource-list--large"><li class="resource-item"><span class="number-badge">1</span><span><strong>Item A</strong><small>Identificação, categoria e prioridade</small></span><span class="resource-item__meta">Abrir</span></li><li class="resource-item"><span class="number-badge">2</span><span><strong>Item B</strong><small>Identificação, categoria e prioridade</small></span><span class="resource-item__meta">Abrir</span></li></ul></article><article class="triage-panel triage-panel--action"><h3>Ação recomendada</h3><ul class="checklist"><li>Abrir o detalhe quando houver dúvida no resultado.</li><li>Registrar o tratamento quando a evidência for suficiente.</li><li>Salvar a pesquisa se o conjunto de filtros for recorrente.</li></ul></article></div></section>
<div class="warning"><strong>Dados sensíveis</strong><p>Oculte informações pessoais em capturas compartilhadas. Informe quais filtros são obrigatórios nesta operação.</p></div>
', 90, true, '2026-08-03 01:37:36.989947+00', '2026-08-03 01:37:37.043624+00', 'migration', 'migration', false, NULL, NULL, 1),
	('10000000-0000-0000-0000-000000000014', 'PAINEL_METRICAS', 'Painel de métricas', 'Configurar execução, acompanhar status, ler indicadores e validar o resultado.', '
<section class="doc-intro"><span class="doc-kicker">Painel de execução</span><h2>Acompanhar uma execução de [processo]</h2><p>Trate a operação como um lote: configure a entrada, acompanhe o andamento e interprete as métricas finais.</p></section>
<section class="doc-section"><h2>Métricas do lote</h2><div class="metric-board"><article class="metric-card"><span class="metric-card__label">Itens processados</span><strong class="metric-card__value">—</strong><p>Total analisado na execução.</p></article><article class="metric-card"><span class="metric-card__label">Itens apontados</span><strong class="metric-card__value">—</strong><p>Quantidade com resultado relevante.</p></article><article class="metric-card"><span class="metric-card__label">Regras / critérios</span><strong class="metric-card__value">—</strong><p>Conjunto usado na execução.</p></article><article class="metric-card"><span class="metric-card__label">Tempo</span><strong class="metric-card__value">—</strong><p>Duração até a conclusão.</p></article></div></section>
<section class="doc-section"><h2>Linha do tempo do status</h2><ol class="pipeline-track"><li class="pipeline-step pipeline-step--ready"><strong>Solicitada</strong><span>Lote criado e aguardando fila.</span></li><li class="pipeline-step pipeline-step--progress"><strong>Em processamento</strong><span>Critérios sendo aplicados aos itens.</span></li><li class="pipeline-step"><strong>Concluída</strong><span>Métricas e resultados disponíveis.</span></li><li class="pipeline-step pipeline-step--risk"><strong>Falha</strong><span>Registrar causa e reprocessar se necessário.</span></li></ol></section>
<section class="doc-section doc-section--soft"><h2>Configuração da execução</h2><div class="content-grid content-grid--2"><article class="rule-card"><h3>Entrada</h3><ul><li>Filtros ou lote de origem.</li><li>Regras, critérios ou ponto de corte.</li><li>Janela temporal considerada.</li></ul></article><article class="rule-card"><h3>Saída esperada</h3><ul><li>Resultados gerados para análise.</li><li>Indicadores do lote.</li><li>Base para comparar com o esperado.</li></ul></article></div></section>
<div class="result-card"><strong>Validação final</strong><p>Confirme status concluído, métricas coerentes com a configuração e se os apontamentos merecem análise detalhada.</p></div>
', 91, true, '2026-08-03 01:37:36.989947+00', '2026-08-03 01:37:37.043624+00', 'migration', 'migration', false, NULL, NULL, 1),
	('10000000-0000-0000-0000-000000000015', 'DOSSIE_DECISAO', 'Dossiê de decisão', 'Identificação do caso, evidências, matriz de parecer e próximos passos.', '
<section class="doc-intro"><span class="doc-kicker">Dossiê de decisão</span><h2>Analisar um [caso]</h2><p>Monte o caso com identificação, evidências e parecer — sem depender de um guia genérico de tela.</p></section>
<section class="doc-section"><div class="dossier-strip"><div><span class="doc-kicker">Identificação</span><h3>Registro / documento</h3><p>Nome, código e origem do apontamento que motivou a análise.</p></div><div><span class="doc-kicker">Contexto</span><h3>Por que abriu</h3><p>Critério, severidade e data do apontamento.</p></div><div><span class="doc-kicker">Responsável</span><h3>Quem decide</h3><p>Perfil autorizado a registrar o parecer neste caso.</p></div></div></section>
<section class="doc-section"><h2>Evidências × decisão</h2><div class="decision-board"><article class="evidence-panel"><h3>Evidências a conferir</h3><ul class="rank-list"><li>Dados apresentados no detalhe.</li><li>Histórico relevante e apontamentos correlatos.</li><li>Critérios que originaram o caso.</li><li>Restrições de sigilo e dados pessoais.</li></ul></article><article class="evidence-panel evidence-panel--decision"><h3>Matriz de parecer</h3><div class="table-wrap"><table><thead><tr><th>Parecer</th><th>Quando aplicar</th><th>Impacto</th></tr></thead><tbody><tr><td><strong>Prosseguir / confirmar</strong></td><td>Evidências sustentam o apontamento</td><td>Descreva o efeito no tratamento</td></tr><tr><td><strong>Descartar</strong></td><td>Não há lastro suficiente</td><td>Registre justificativa</td></tr><tr><td><strong>Escalar</strong></td><td>Exige alçada superior ou outra área</td><td>Indique o próximo responsável</td></tr></tbody></table></div></article></div></section>
<section class="doc-section"><h2>Encerramento do caso</h2><ul class="status-list"><li class="status-item status-item--progress"><span>Parecer registrado</span><strong>Em andamento</strong></li><li class="status-item"><span>Retorno à fila de origem</span><strong>Pendente</strong></li><li class="status-item status-item--done"><span>Caso concluído na análise</span><strong>Feito</strong></li></ul></section>
<div class="callout"><strong>Artigos relacionados</strong><p>Vincule a consulta de origem, a execução que gerou o caso e a regra ou critério aplicado.</p></div>
', 92, true, '2026-08-03 01:37:36.989947+00', '2026-08-03 01:37:37.043624+00', 'migration', 'migration', false, NULL, NULL, 1),
	('10000000-0000-0000-0000-000000000016', 'ESPECIFICACAO_REGRA', 'Especificação de regra', 'Identidade da regra, condições SE/ENTÃO, parâmetros, versão e impacto.', '
<section class="doc-intro"><span class="doc-kicker">Especificação de regra</span><h2>Documentar uma regra de [assunto]</h2><p>Descreva a regra como um contrato: quando dispara, o que produz e qual versão está vigente.</p></section>
<section class="doc-section"><div class="spec-card"><div class="spec-card__meta"><span class="status-badge status-badge--required">Versão vigente</span><span class="status-badge">Escopo</span></div><h3>Nome da regra</h3><p>Resuma a finalidade em uma frase e indique processos ou resultados influenciados.</p><div class="spec-card__grid"><div><strong>Código / chave</strong><span>Identificador estável da regra</span></div><div><strong>Owner</strong><span>Área responsável pela manutenção</span></div><div><strong>Última revisão</strong><span>Data e motivação da alteração</span></div></div></div></section>
<section class="doc-section"><h2>Condições SE → ENTÃO</h2><div class="condition-stack"><article class="condition-block"><span class="condition-block__label">SE</span><h3>Condição de entrada</h3><p>Liste critérios, limiares e combinações que disparam a regra.</p></article><article class="condition-block condition-block--then"><span class="condition-block__label">ENTÃO</span><h3>Efeito esperado</h3><p>Descreva pontuação, classificação, notificação ou exclusão do fluxo.</p></article></div></section>
<section class="doc-section"><h2>Parâmetros da regra</h2><div class="table-wrap"><table><thead><tr><th>Parâmetro</th><th>Tipo</th><th>Valor de referência</th><th>Efeito se alterar</th></tr></thead><tbody><tr><td>Limiar / ponto de corte</td><td>Numérico</td><td>Informe o valor vigente</td><td>Muda volume de resultados</td></tr><tr><td>Filtro de elegibilidade</td><td>Lista / flag</td><td>Informe o conjunto</td><td>Inclui ou exclui registros</td></tr><tr><td>Severidade / prioridade</td><td>Enumeração</td><td>Alta / média / baixa</td><td>Prioriza a fila de trabalho</td></tr></tbody></table></div></section>
<section class="doc-section"><h2>Ciclo de vida da versão</h2><ol class="flow-strip"><li><strong>Rascunho</strong><span>Altere sem publicar.</span></li><li><strong>Validar</strong><span>Teste em ambiente controlado.</span></li><li><strong>Publicar</strong><span>Ative a versão.</span></li><li><strong>Monitorar</strong><span>Acompanhe impacto.</span></li></ol></section>
<div class="warning"><strong>Antes de publicar</strong><p>Confirme autorização, testes obrigatórios e plano de rollback para a versão anterior.</p></div>
', 93, true, '2026-08-03 01:37:36.989947+00', '2026-08-03 01:37:37.043624+00', 'migration', 'migration', false, NULL, NULL, 1),
	('10000000-0000-0000-0000-000000000017', 'CATALOGO_PARAMETROS', 'Catálogo de parâmetros', 'Grupos, ficha do parâmetro, dependências e impacto da alteração.', '
<section class="doc-intro"><span class="doc-kicker">Catálogo corporativo</span><h2>Manter parâmetros de [assunto]</h2><p>Organize o parâmetro como item de catálogo: grupo, ficha, quem consome e o que quebra se mudar.</p></section>
<section class="doc-section"><h2>Grupos do catálogo</h2><div class="content-grid content-grid--3"><article class="topic-card"><span class="topic-card__icon">01</span><h3>Corporativos</h3><p>Dados mestres compartilhados entre módulos.</p></article><article class="topic-card"><span class="topic-card__icon">02</span><h3>Auxiliares</h3><p>Listas de apoio a telas e regras.</p></article><article class="topic-card"><span class="topic-card__icon">03</span><h3>Operacionais</h3><p>Valores que alteram processamentos e rotinas.</p></article></div></section>
<section class="doc-section"><h2>Ficha do parâmetro</h2><div class="table-wrap"><table class="dictionary-table"><thead><tr><th>Atributo</th><th>Conteúdo</th><th>Obrigatório?</th><th>Observação</th></tr></thead><tbody><tr><td><strong>Código</strong></td><td>Identificador estável</td><td><span class="status-badge status-badge--required">Sim</span></td><td>Não reutilize códigos desativados</td></tr><tr><td><strong>Nome</strong></td><td>Rótulo de negócio</td><td><span class="status-badge status-badge--required">Sim</span></td><td>Use linguagem do operador</td></tr><tr><td><strong>Vigência</strong></td><td>Início, fim e status</td><td><span class="status-badge status-badge--required">Sim</span></td><td>Explique ativação e desativação</td></tr><tr><td><strong>Valor / conteúdo</strong></td><td>Dado efetivamente usado</td><td><span class="status-badge">Conforme tipo</span></td><td>Formato, unidade e limites</td></tr></tbody></table></div></section>
<section class="doc-section"><h2>Quem consome este parâmetro</h2><div class="dependency-list"><div class="resource-item"><span class="number-badge">R</span><span><strong>Regras / critérios</strong><small>Quais regras leem este valor</small></span><span class="resource-item__meta">Dependência</span></div><div class="resource-item"><span class="number-badge">P</span><span><strong>Processos</strong><small>Impacto em lotes, filas ou rotinas</small></span><span class="resource-item__meta">Dependência</span></div><div class="resource-item"><span class="number-badge">T</span><span><strong>Telas / relatórios</strong><small>Efeito na classificação, filtros ou exibição</small></span><span class="resource-item__meta">Dependência</span></div></div></section>
<section class="doc-section"><div class="steps"><h2>Manutenção segura</h2><ol><li>Localize o grupo e abra o registro (ou inicie um novo).</li><li>Atualize apenas os atributos necessários na ficha.</li><li>Revise dependências listadas acima.</li><li>Salve e confira vigência na listagem do catálogo.</li></ol></div></section>
<div class="warning"><strong>Impacto operacional</strong><p>Registre processos, filas ou relatórios afetados e se a alteração exige comunicação prévia.</p></div>
', 94, true, '2026-08-03 01:37:36.989947+00', '2026-08-03 01:37:37.043624+00', 'migration', 'migration', false, NULL, NULL, 1);

INSERT INTO public.tb_pagina_template_versao (id, template_id, numero, nome, descricao, conteudo_html, ativo, projeto_id, cliente_id, created_at, updated_at, created_by, updated_by) VALUES
	('8382df05-75d2-4f65-9988-05297f0d79f1', '10000000-0000-0000-0000-000000000001', 1, 'Guia de funcionalidade', 'Apresenta objetivo, visão da tela, pontos numerados, regras e resultado esperado.', '
<section class="doc-intro"><span class="doc-kicker">Guia da funcionalidade</span><h2>Visão geral da funcionalidade</h2><p>Apresente em uma frase o que o recurso permite fazer e para quem ele foi criado.</p></section>
<div class="objective-card"><p><strong>Objetivo desta funcionalidade</strong></p><p>Explique o ganho para o usuário e o resultado de negócio esperado.</p></div>
<section class="doc-section"><h2>Visão da tela</h2><p>Use esta área para orientar visualmente os principais pontos da interface.</p><figure class="screen-frame"><div class="screen-placeholder"><strong>Insira aqui uma captura da tela</strong><span>Use a ferramenta de imagem do editor e substitua este bloco.</span></div><figcaption>Tela principal da funcionalidade.</figcaption></figure></section>
<section class="doc-section"><h2>Principais elementos</h2><div class="annotation-grid"><article class="annotation-card"><h3>Acesso principal</h3><p>Indique onde o usuário inicia a operação.</p></article><article class="annotation-card"><h3>Área de trabalho</h3><p>Explique onde os dados são exibidos ou preenchidos.</p></article><article class="annotation-card"><h3>Ação de confirmação</h3><p>Mostre como concluir e salvar a operação.</p></article></div></section>
<section class="doc-section"><h2>Regras e orientações</h2><div class="content-grid content-grid--2"><article class="rule-card"><h3>Regra de negócio</h3><p>Descreva uma validação importante e seu impacto.</p></article><article class="rule-card"><h3>Boa prática</h3><p>Registre uma recomendação que evite erros recorrentes.</p></article></div></section>
<div class="result-card"><strong>Resultado esperado</strong><p>Informe o que será apresentado após a conclusão bem-sucedida.</p></div>
', true, NULL, NULL, '2026-08-03 01:37:36.839875+00', '2026-08-03 01:37:36.890464+00', 'migration', 'migration'),
	('b2e061a5-62e7-49aa-8d59-102dd376c9c4', '10000000-0000-0000-0000-000000000002', 1, 'Passo a passo visual', 'Guia operacional com preparação, fluxo horizontal, etapas e validação final.', '
<section class="doc-intro"><span class="doc-kicker">Guia operacional</span><h2>Como realizar o procedimento</h2><p>Resuma o procedimento, quando ele deve ser executado e o tempo estimado.</p></section>
<div class="objective-card"><p><strong>Antes de começar</strong></p><p>Liste permissões, dados e condições necessárias para seguir este guia.</p></div>
<section class="doc-section"><h2>Fluxo do procedimento</h2><ol class="flow-strip"><li><strong>Acessar</strong><span>Abra a tela indicada.</span></li><li><strong>Preencher</strong><span>Informe os dados solicitados.</span></li><li><strong>Revisar</strong><span>Confira as informações.</span></li><li><strong>Concluir</strong><span>Confirme a operação.</span></li></ol></section>
<section class="doc-section"><h2>Passo a passo detalhado</h2><div class="screen-grid"><article class="guide-card"><span class="guide-card__number">1</span><div class="screen-placeholder screen-placeholder--compact"><strong>Captura da etapa 1</strong><span>Insira a imagem correspondente.</span></div><h3>Acesse a funcionalidade</h3><p>Indique o caminho de navegação e o ponto de entrada.</p></article><article class="guide-card"><span class="guide-card__number">2</span><div class="screen-placeholder screen-placeholder--compact"><strong>Captura da etapa 2</strong><span>Insira a imagem correspondente.</span></div><h3>Preencha e revise</h3><p>Explique os dados necessários e as validações da tela.</p></article><article class="guide-card"><span class="guide-card__number">3</span><div class="screen-placeholder screen-placeholder--compact"><strong>Captura da etapa 3</strong><span>Insira a imagem correspondente.</span></div><h3>Confirme a operação</h3><p>Mostre a ação final e a mensagem apresentada.</p></article></div></section>
<div class="result-card"><strong>Como validar</strong><p>Explique como confirmar visualmente que o procedimento funcionou.</p></div>
', true, NULL, NULL, '2026-08-03 01:37:36.839875+00', '2026-08-03 01:37:36.890464+00', 'migration', 'migration'),
	('6992e98d-4d90-4892-94e0-0bd2aa3beaac', '10000000-0000-0000-0000-000000000003', 1, 'Cadastro ou edição', 'Documenta uma tela de cadastro com captura, marcações, regras e passos.', '
<section class="doc-intro"><span class="doc-kicker">Cadastro e edição</span><h2>Cadastro de [entidade]</h2><p>Explique quando este cadastro deve ser usado e o que será registrado.</p></section>
<div class="objective-card"><p><strong>Objetivo desta tela</strong></p><p>Descreva o valor do cadastro para a operação e quem pode realizá-lo.</p></div>
<section class="doc-section"><h2>Visão da tela</h2><figure class="screen-frame"><div class="screen-placeholder"><strong>Insira a captura da tela de cadastro</strong><span>Prefira uma imagem limpa, com os campos principais visíveis.</span></div><figcaption>Visão geral da tela de cadastro.</figcaption></figure></section>
<section class="doc-section"><h2>Elementos da tela</h2><div class="annotation-grid"><article class="annotation-card"><h3>Campo principal</h3><p>Informe formato, limite e exemplo de preenchimento.</p></article><article class="annotation-card"><h3>Campos complementares</h3><p>Explique quando cada informação deve ser preenchida.</p></article><article class="annotation-card"><h3>Status ou opção</h3><p>Descreva o efeito de cada valor disponível.</p></article><article class="annotation-card"><h3>Ações</h3><p>Detalhe os botões Salvar, Cancelar e outras ações.</p></article></div></section>
<section class="doc-section"><div class="content-grid content-grid--2"><article class="rule-card"><h2>Regras de negócio</h2><ul class="checklist"><li>Registre uma validação obrigatória.</li><li>Explique duplicidade, limites ou dependências.</li></ul></article><article class="rule-card"><h2>Como cadastrar</h2><ol><li>Acesse a tela.</li><li>Preencha os campos indicados.</li><li>Revise e selecione <strong>Salvar</strong>.</li></ol></article></div></section>
<div class="callout"><strong>Artigos relacionados</strong><p>Inclua links para consulta, edição ou processos ligados a este cadastro.</p></div>
', true, NULL, NULL, '2026-08-03 01:37:36.839875+00', '2026-08-03 01:37:36.890464+00', 'migration', 'migration'),
	('6b4f7e34-2238-4d55-8f16-ad81107f31d5', '10000000-0000-0000-0000-000000000004', 1, 'Consulta ou listagem', 'Explica filtros, listagem, ações disponíveis, regras e exemplos de uso.', '
<section class="doc-intro"><span class="doc-kicker">Consulta e listagem</span><h2>Consulta de [registros]</h2><p>Apresente as informações disponíveis e as situações em que esta consulta é útil.</p></section>
<div class="objective-card"><p><strong>Objetivo desta tela</strong></p><p>Explique quais decisões ou tarefas a consulta ajuda o usuário a realizar.</p></div>
<section class="doc-section"><h2>Visão da tela</h2><figure class="screen-frame"><div class="screen-placeholder"><strong>Insira a captura da consulta</strong><span>Deixe filtros, tabela e ações visíveis.</span></div><figcaption>Visão geral dos filtros e resultados.</figcaption></figure></section>
<section class="doc-section"><h2>Elementos da tela</h2><div class="annotation-grid"><article class="annotation-card"><h3>Filtros</h3><p>Descreva os principais critérios de pesquisa.</p></article><article class="annotation-card"><h3>Pesquisar e limpar</h3><p>Explique o comportamento de cada ação.</p></article><article class="annotation-card"><h3>Resultados</h3><p>Apresente as colunas e a ordenação padrão.</p></article><article class="annotation-card"><h3>Ações por registro</h3><p>Detalhe visualizar, editar e excluir.</p></article></div></section>
<section class="doc-section"><div class="content-grid content-grid--2"><article class="rule-card"><h2>Regras de negócio</h2><ul><li>Informe limites e combinações de filtros.</li><li>Explique visibilidade e permissões.</li></ul></article><article class="rule-card"><h2>Exemplos de uso</h2><ul><li>Localizar registros por nome ou período.</li><li>Filtrar itens por situação.</li><li>Abrir os detalhes de um resultado.</li></ul></article></div></section>
', true, NULL, NULL, '2026-08-03 01:37:36.839875+00', '2026-08-03 01:37:36.890464+00', 'migration', 'migration'),
	('58387fca-bd68-4c3a-9168-91ef1740ed7d', '10000000-0000-0000-0000-000000000007', 1, 'Dicionário de campos', 'Catálogo visual de campos com obrigatoriedade, exemplo e impacto no negócio.', '
<section class="doc-intro"><span class="doc-kicker">Referência de dados</span><h2>Dicionário de campos — [tela]</h2><p>Documente o significado de cada campo e o impacto de um preenchimento incorreto.</p></section>
<div class="objective-card"><p><strong>Objetivo deste dicionário</strong></p><p>Padronizar o entendimento funcional e apoiar usuários, produto, suporte e desenvolvimento.</p></div>
<section class="doc-section"><h2>Visão da tela</h2><figure class="screen-frame"><div class="screen-placeholder"><strong>Insira a captura com os campos numerados</strong><span>Use os números da imagem na primeira coluna da tabela.</span></div><figcaption>Campos mapeados para o dicionário abaixo.</figcaption></figure></section>
<section class="doc-section"><h2>Descrição dos campos</h2><div class="table-wrap"><table class="dictionary-table"><thead><tr><th>#</th><th>Campo</th><th>Descrição</th><th>Obrigatório?</th><th>Exemplo</th><th>Impacto no negócio</th></tr></thead><tbody><tr><td><span class="number-badge">1</span></td><td><strong>Nome do campo</strong></td><td>Explique finalidade, formato e origem da informação.</td><td><span class="status-badge status-badge--required">Sim</span></td><td>Valor de exemplo</td><td>Descreva o efeito deste dado nos processos.</td></tr><tr><td><span class="number-badge">2</span></td><td><strong>Outro campo</strong></td><td>Detalhe regras, limites e dependências.</td><td><span class="status-badge">Não</span></td><td>Valor de exemplo</td><td>Informe relatórios, integrações ou decisões afetadas.</td></tr></tbody></table></div></section>
<section class="doc-section"><h2>Observações importantes</h2><div class="content-grid content-grid--3"><article class="rule-card"><h3>Validações</h3><p>Liste formatos e mensagens de erro.</p></article><article class="rule-card"><h3>Dependências</h3><p>Explique campos condicionais e relacionamentos.</p></article><article class="rule-card"><h3>Segurança</h3><p>Indique dados sensíveis e restrições de acesso.</p></article></div></section>
', true, NULL, NULL, '2026-08-03 01:37:36.890464+00', '2026-08-03 01:37:36.890464+00', 'migration', 'migration'),
	('efe38e48-18a7-4d36-932a-8c0ce1576b1f', '10000000-0000-0000-0000-000000000008', 1, 'Fluxo de processo', 'Documenta etapas, telas envolvidas, regras e resumo de um processo ponta a ponta.', '
<section class="doc-intro"><span class="doc-kicker">Processo ponta a ponta</span><h2>Processo de [nome do processo]</h2><p>Explique o início, o fim e os participantes deste fluxo.</p></section>
<div class="objective-card"><p><strong>Objetivo do processo</strong></p><p>Descreva o resultado de negócio, as áreas envolvidas e o tempo esperado.</p></div>
<section class="doc-section"><h2>Visão geral do fluxo</h2><ol class="flow-strip"><li><strong>Solicitação</strong><span>O processo é iniciado.</span></li><li><strong>Análise</strong><span>Os dados são validados.</span></li><li><strong>Aprovação</strong><span>O responsável decide.</span></li><li><strong>Conclusão</strong><span>O resultado é registrado.</span></li></ol></section>
<section class="doc-section"><h2>Telas envolvidas</h2><div class="screen-grid"><article class="guide-card"><span class="guide-card__number">1</span><div class="screen-placeholder screen-placeholder--compact"><strong>Tela de entrada</strong><span>Insira uma captura.</span></div><h3>Início do processo</h3><p>Explique como a solicitação é registrada.</p></article><article class="guide-card"><span class="guide-card__number">2</span><div class="screen-placeholder screen-placeholder--compact"><strong>Tela de análise</strong><span>Insira uma captura.</span></div><h3>Análise e decisão</h3><p>Mostre validações, responsáveis e ações.</p></article><article class="guide-card"><span class="guide-card__number">3</span><div class="screen-placeholder screen-placeholder--compact"><strong>Tela final</strong><span>Insira uma captura.</span></div><h3>Conclusão</h3><p>Descreva o retorno e os registros gerados.</p></article></div></section>
<section class="doc-section"><h2>Regras do processo</h2><div class="content-grid content-grid--3"><article class="rule-card"><h3>Entrada</h3><p>Informe critérios para iniciar o fluxo.</p></article><article class="rule-card"><h3>Decisão</h3><p>Registre aprovações, exceções e alçadas.</p></article><article class="rule-card"><h3>Saída</h3><p>Explique notificações e dados gerados.</p></article></div></section>
<section class="doc-section"><h2>Resumo das etapas</h2><div class="table-wrap"><table><thead><tr><th>Etapa</th><th>Responsável</th><th>Entrada</th><th>Saída</th></tr></thead><tbody><tr><td>Solicitação</td><td>Perfil ou área</td><td>Dados necessários</td><td>Registro criado</td></tr><tr><td>Análise</td><td>Perfil ou área</td><td>Registro pendente</td><td>Decisão registrada</td></tr></tbody></table></div></section>
', true, NULL, NULL, '2026-08-03 01:37:36.890464+00', '2026-08-03 01:37:36.890464+00', 'migration', 'migration'),
	('d752fe15-eedf-443e-a937-81f3e48c30a4', '10000000-0000-0000-0000-000000000005', 1, 'Perguntas frequentes', 'Organiza atalhos por assunto e dúvidas recorrentes em cartões objetivos.', '
<section class="doc-intro"><span class="doc-kicker">Central de dúvidas</span><h2>Perguntas frequentes</h2><p>Reúna respostas curtas e diretas para as dúvidas mais recorrentes.</p></section>
<section class="doc-section"><h2>Acesso rápido</h2><div class="content-grid content-grid--3"><article class="topic-card"><span class="topic-card__icon">01</span><h3>Primeiros passos</h3><p>Dúvidas sobre acesso e configuração inicial.</p></article><article class="topic-card"><span class="topic-card__icon">02</span><h3>Operação</h3><p>Orientações para as tarefas do dia a dia.</p></article><article class="topic-card"><span class="topic-card__icon">03</span><h3>Erros comuns</h3><p>Soluções rápidas para situações conhecidas.</p></article></div></section>
<section class="doc-section faq-list"><article class="faq-item"><h3>Quando devo utilizar esta funcionalidade?</h3><p>Responda objetivamente e indique o cenário recomendado.</p></article><article class="faq-item"><h3>O que fazer quando a operação não for concluída?</h3><p>Indique verificações iniciais e quando acionar o suporte.</p></article><article class="faq-item"><h3>Posso desfazer esta ação?</h3><p>Explique se a operação é reversível e quais cuidados tomar.</p></article></section>
', true, NULL, NULL, '2026-08-03 01:37:36.839875+00', '2026-08-03 01:37:36.890464+00', 'migration', 'migration'),
	('0f9afdcc-db66-4bf5-97cd-75279eec9ccc', '10000000-0000-0000-0000-000000000006', 1, 'Solução de problemas', 'Relaciona sintomas, causas, diagnóstico visual e ações corretivas.', '
<section class="doc-intro"><span class="doc-kicker">Diagnóstico e solução</span><h2>Problema: [sintoma principal]</h2><p>Descreva a mensagem, o comportamento observado e em qual etapa ocorre.</p></section>
<div class="objective-card"><p><strong>Antes de investigar</strong></p><p>Registre versão, usuário, horário e evidências necessárias para reproduzir o problema.</p></div>
<section class="doc-section"><div class="content-grid content-grid--2"><article class="rule-card"><h2>Sintomas</h2><ul><li>Mensagem apresentada.</li><li>Comportamento inesperado.</li><li>Condição em que acontece.</li></ul></article><article class="rule-card"><h2>Possíveis causas</h2><ul><li>Permissão ou configuração.</li><li>Dado inválido ou incompleto.</li><li>Indisponibilidade de integração.</li></ul></article></div></section>
<section class="doc-section"><h2>Como resolver</h2><ol class="flow-strip"><li><strong>Verificar</strong><span>Confirme dados e acessos.</span></li><li><strong>Corrigir</strong><span>Aplique a orientação.</span></li><li><strong>Testar</strong><span>Repita a operação.</span></li><li><strong>Registrar</strong><span>Documente o resultado.</span></li></ol></section>
<section class="doc-section"><h2>Evidência visual</h2><figure class="screen-frame"><div class="screen-placeholder"><strong>Insira a captura da mensagem ou comportamento</strong><span>Oculte dados pessoais e destaque a área relevante.</span></div><figcaption>Exemplo do problema e do ponto que deve ser verificado.</figcaption></figure></section>
<div class="warning"><strong>Quando acionar o suporte</strong><p>Informe os critérios de escalonamento e quais evidências devem ser enviadas.</p></div>
', true, NULL, NULL, '2026-08-03 01:37:36.839875+00', '2026-08-03 01:37:36.890464+00', 'migration', 'migration'),
	('b12094bb-ddef-496d-9f29-ac286493af62', '10000000-0000-0000-0000-000000000009', 1, 'Central de ajuda', 'Página inicial com acessos rápidos, destaques, tipos de documentação e conteúdo recente.', '
<section class="doc-intro doc-intro--center"><span class="doc-kicker">Portal de conhecimento</span><h2>Central de ajuda [produto]</h2><p>Apresente o propósito da central e ajude o usuário a encontrar rapidamente o conteúdo certo.</p></section>
<section class="doc-section"><h2>Acesso rápido</h2><div class="content-grid content-grid--3"><article class="topic-card"><span class="topic-card__icon">01</span><h3>Primeiros passos</h3><p>Conceitos essenciais para começar com segurança.</p></article><article class="topic-card"><span class="topic-card__icon">02</span><h3>Cadastros</h3><p>Orientações para criar e manter informações.</p></article><article class="topic-card"><span class="topic-card__icon">03</span><h3>Operações</h3><p>Fluxos e procedimentos das rotinas principais.</p></article><article class="topic-card"><span class="topic-card__icon">04</span><h3>Relatórios</h3><p>Consultas, indicadores e exportações.</p></article><article class="topic-card"><span class="topic-card__icon">05</span><h3>Configurações</h3><p>Personalização, acessos e regras do sistema.</p></article><article class="topic-card"><span class="topic-card__icon">06</span><h3>Financeiro</h3><p>Contas, títulos, recebimentos e pagamentos.</p></article></div></section>
<section class="doc-section"><h2>Guias em destaque</h2><div class="screen-grid"><article class="guide-card"><span class="guide-card__number">1</span><div class="screen-placeholder screen-placeholder--compact"><strong>Imagem do guia</strong><span>Insira uma captura de destaque.</span></div><h3>Guia visual em destaque</h3><p>Resuma o resultado que o usuário alcançará.</p></article><article class="guide-card"><span class="guide-card__number">2</span><div class="screen-placeholder screen-placeholder--compact"><strong>Imagem do guia</strong><span>Insira uma captura de destaque.</span></div><h3>Procedimento recomendado</h3><p>Apresente uma rotina importante do sistema.</p></article><article class="guide-card"><span class="guide-card__number">3</span><div class="screen-placeholder screen-placeholder--compact"><strong>Imagem do guia</strong><span>Insira uma captura de destaque.</span></div><h3>Relatório mais acessado</h3><p>Mostre como transformar dados em decisão.</p></article></div></section>
<section class="doc-section"><div class="content-grid content-grid--2"><article class="rule-card"><h2>Artigos recentes</h2><div class="resource-list"><div class="resource-item"><strong>Nome do artigo publicado</strong><span>Atualizado recentemente</span></div><div class="resource-item"><strong>Outro conteúdo importante</strong><span>Categoria do artigo</span></div><div class="resource-item"><strong>Boas práticas para usuários</strong><span>Tempo de leitura</span></div></div></article><article class="rule-card"><h2>Perguntas frequentes</h2><div class="faq-list"><article class="faq-item"><h3>Como encontro uma funcionalidade?</h3><p>Oriente o uso da busca e das categorias.</p></article><article class="faq-item"><h3>Onde solicito ajuda?</h3><p>Indique os canais disponíveis.</p></article></div></article></div></section>
', true, NULL, NULL, '2026-08-03 01:37:36.905124+00', '2026-08-03 01:37:36.905124+00', 'migration', 'migration'),
	('78ba9c30-c092-4511-92d2-335060ad1a16', '10000000-0000-0000-0000-000000000010', 1, 'Índice de categoria', 'Organiza artigos por assunto com filtros, metadados, conteúdos populares e tutoriais.', '
<section class="doc-intro"><span class="doc-kicker">Módulo ou categoria</span><h2>[Nome da categoria]</h2><p>Explique quais temas e atividades o usuário encontrará nesta seção.</p></section>
<div class="filter-chips"><p><span class="filter-chip filter-chip--active">Todos</span><span class="filter-chip">Assunto 1</span><span class="filter-chip">Assunto 2</span><span class="filter-chip">Importação e exportação</span><span class="filter-chip">Permissões</span></p></div>
<section class="doc-section"><h2>Guias disponíveis</h2><div class="resource-list resource-list--large"><article class="resource-item"><span class="number-badge">1</span><span><strong>Como realizar a atividade principal</strong><small>Explique o objetivo deste artigo em uma frase.</small></span><span class="resource-item__meta">6 min · atualizado recentemente</span></article><article class="resource-item"><span class="number-badge">2</span><span><strong>Como configurar uma opção</strong><small>Apresente o resultado esperado do guia.</small></span><span class="resource-item__meta">7 min · guia visual</span></article><article class="resource-item"><span class="number-badge">3</span><span><strong>Importação de informações</strong><small>Oriente sobre formatos, regras e validações.</small></span><span class="resource-item__meta">9 min · passo a passo</span></article><article class="resource-item"><span class="number-badge">4</span><span><strong>Exportação de informações</strong><small>Mostre como gerar e utilizar o arquivo.</small></span><span class="resource-item__meta">6 min · referência</span></article></div></section>
<section class="doc-section"><div class="content-grid content-grid--2"><article class="rule-card"><h2>Artigos populares</h2><ol class="rank-list"><li>Conteúdo mais acessado da categoria</li><li>Dúvida recorrente dos usuários</li><li>Boas práticas recomendadas</li><li>Solução para um erro conhecido</li></ol></article><article class="rule-card"><h2>Tutoriais relacionados</h2><div class="content-grid content-grid--2"><article class="topic-card"><span class="topic-card__icon">▶</span><h3>Tutorial visual</h3><p>Inclua duração e benefício.</p></article><article class="topic-card"><span class="topic-card__icon">▶</span><h3>Demonstração prática</h3><p>Explique o que será demonstrado.</p></article></div></article></div></section>
', true, NULL, NULL, '2026-08-03 01:37:36.905124+00', '2026-08-03 01:37:36.905124+00', 'migration', 'migration'),
	('b185fb25-04a6-425c-9558-6911eee81672', '10000000-0000-0000-0000-000000000011', 1, 'Primeiros passos', 'Jornada inicial com etapas, tutoriais, checklist de implantação e materiais complementares.', '
<section class="doc-intro"><span class="doc-kicker">Boas-vindas</span><h2>Primeiros passos no [produto]</h2><p>Apresente a jornada inicial para que o usuário comece com confiança.</p></section>
<section class="doc-section"><h2>Jornada inicial</h2><div class="journey-grid"><article class="journey-card"><span class="journey-card__number">1</span><h3>Acesso ao sistema</h3><p>Explique como entrar e navegar pela primeira vez.</p></article><article class="journey-card"><span class="journey-card__number">2</span><h3>Segurança inicial</h3><p>Oriente senha, autenticação e proteção da conta.</p></article><article class="journey-card"><span class="journey-card__number">3</span><h3>Configurar perfil</h3><p>Mostre preferências e informações pessoais.</p></article><article class="journey-card"><span class="journey-card__number">4</span><h3>Criar primeiro cadastro</h3><p>Ajude o usuário a registrar a primeira informação.</p></article><article class="journey-card"><span class="journey-card__number">5</span><h3>Consultar resultados</h3><p>Apresente consultas e relatórios essenciais.</p></article></div></section>
<section class="doc-section"><h2>Tutoriais visuais</h2><div class="screen-grid"><article class="guide-card"><div class="screen-placeholder screen-placeholder--compact"><strong>Imagem do tutorial</strong><span>Insira a captura da etapa.</span></div><h3>Como acessar o sistema</h3><p>Informe duração e aprendizado.</p></article><article class="guide-card"><div class="screen-placeholder screen-placeholder--compact"><strong>Imagem do tutorial</strong><span>Insira a captura da etapa.</span></div><h3>Configurando seu perfil</h3><p>Mostre o resultado do tutorial.</p></article><article class="guide-card"><div class="screen-placeholder screen-placeholder--compact"><strong>Imagem do tutorial</strong><span>Insira a captura da etapa.</span></div><h3>Visão geral de relatórios</h3><p>Apresente os principais indicadores.</p></article></div></section>
<section class="doc-section"><div class="content-grid content-grid--2"><article class="rule-card"><h2>Checklist de implantação</h2><ul class="status-list"><li class="status-item status-item--done"><span>Acessar com usuário administrador</span><strong>Concluído</strong></li><li class="status-item status-item--done"><span>Configurar perfil e preferências</span><strong>Concluído</strong></li><li class="status-item status-item--progress"><span>Criar primeiro cadastro</span><strong>Em andamento</strong></li><li class="status-item"><span>Consultar ou gerar um relatório</span><strong>Pendente</strong></li></ul></article><article class="rule-card"><h2>Materiais complementares</h2><div class="content-grid content-grid--3"><article class="topic-card"><span class="topic-card__icon">?</span><h3>FAQ</h3><p>Dúvidas comuns.</p></article><article class="topic-card"><span class="topic-card__icon">▶</span><h3>Vídeos</h3><p>Tutoriais rápidos.</p></article><article class="topic-card"><span class="topic-card__icon">A–Z</span><h3>Glossário</h3><p>Termos do sistema.</p></article></div></article></div></section>
', true, NULL, NULL, '2026-08-03 01:37:36.905124+00', '2026-08-03 01:37:36.905124+00', 'migration', 'migration'),
	('51e45e4d-6d6a-4b0e-8846-2b0543fed030', '10000000-0000-0000-0000-000000000012', 1, 'Guia de relatório', 'Documenta filtros, período, agrupamento, gráfico, tabela, exportação e boas práticas.', '
<section class="doc-intro"><span class="doc-kicker">Relatórios e indicadores</span><h2>Como gerar o relatório de [assunto]</h2><p>Explique como analisar dados, acompanhar indicadores e apoiar decisões.</p></section>
<div class="objective-card"><p><strong>Objetivo de negócio</strong></p><p>Descreva quais decisões este relatório apoia e quais resultados devem ser acompanhados.</p></div>
<section class="doc-section"><h2>Visão do relatório</h2><figure class="screen-frame"><div class="screen-placeholder"><strong>Insira a captura completa do relatório</strong><span>Mostre filtros, gráfico, tabela e ação de exportação.</span></div><figcaption>Visão geral do relatório e seus principais componentes.</figcaption></figure></section>
<section class="doc-section"><h2>Elementos da tela</h2><div class="annotation-grid"><article class="annotation-card"><h3>Filtros</h3><p>Liste os critérios e a forma como são combinados.</p></article><article class="annotation-card"><h3>Período</h3><p>Explique datas disponíveis e valores padrão.</p></article><article class="annotation-card"><h3>Agrupamento</h3><p>Descreva dia, semana, mês ou outra dimensão.</p></article><article class="annotation-card"><h3>Gráfico</h3><p>Oriente a leitura das séries e indicadores.</p></article><article class="annotation-card"><h3>Tabela</h3><p>Explique colunas, totais e detalhamento.</p></article><article class="annotation-card"><h3>Exportação</h3><p>Informe formatos e cuidados com os dados.</p></article></div></section>
<section class="doc-section"><div class="content-grid content-grid--2"><article class="rule-card"><h2>Regras de negócio</h2><ul class="checklist"><li>Explique como filtros são aplicados.</li><li>Informe as permissões necessárias.</li><li>Registre limites de período ou volume.</li></ul></article><article class="rule-card"><h2>Boas práticas</h2><div class="content-grid content-grid--2"><article class="topic-card"><h3>Defina o objetivo</h3><p>Saiba o que precisa analisar.</p></article><article class="topic-card"><h3>Compare períodos</h3><p>Identifique padrões e tendências.</p></article><article class="topic-card"><h3>Use filtros com critério</h3><p>Reduza ruído nos resultados.</p></article><article class="topic-card"><h3>Exporte e compartilhe</h3><p>Apoie decisões em equipe.</p></article></div></article></div></section>
<div class="related-links"><p><strong>Guias relacionados</strong><span>Personalizar colunas</span><span>Agendar relatório</span><span>Exportar dados</span></p></div>
', true, NULL, NULL, '2026-08-03 01:37:36.905124+00', '2026-08-03 01:37:36.905124+00', 'migration', 'migration');
