-- Amplia o catálogo com estruturas observadas nas páginas de entrada, categoria,
-- onboarding e relatórios. Páginas existentes continuam sem alteração.

INSERT INTO tb_pagina_template
  (id, codigo, nome, descricao, conteudo_html, ordem, ativo, created_by, updated_by)
VALUES
  ('10000000-0000-0000-0000-000000000009', 'CENTRAL_AJUDA', 'Central de ajuda',
   'Página inicial com acessos rápidos, destaques, tipos de documentação e conteúdo recente.', $html$
<section class="doc-intro doc-intro--center"><span class="doc-kicker">Portal de conhecimento</span><h2>Central de ajuda [produto]</h2><p>Apresente o propósito da central e ajude o usuário a encontrar rapidamente o conteúdo certo.</p></section>
<section class="doc-section"><h2>Acesso rápido</h2><div class="content-grid content-grid--3"><article class="topic-card"><span class="topic-card__icon">01</span><h3>Primeiros passos</h3><p>Conceitos essenciais para começar com segurança.</p></article><article class="topic-card"><span class="topic-card__icon">02</span><h3>Cadastros</h3><p>Orientações para criar e manter informações.</p></article><article class="topic-card"><span class="topic-card__icon">03</span><h3>Operações</h3><p>Fluxos e procedimentos das rotinas principais.</p></article><article class="topic-card"><span class="topic-card__icon">04</span><h3>Relatórios</h3><p>Consultas, indicadores e exportações.</p></article><article class="topic-card"><span class="topic-card__icon">05</span><h3>Configurações</h3><p>Personalização, acessos e regras do sistema.</p></article><article class="topic-card"><span class="topic-card__icon">06</span><h3>Financeiro</h3><p>Contas, títulos, recebimentos e pagamentos.</p></article></div></section>
<section class="doc-section"><h2>Guias em destaque</h2><div class="screen-grid"><article class="guide-card"><span class="guide-card__number">1</span><div class="screen-placeholder screen-placeholder--compact"><strong>Imagem do guia</strong><span>Insira uma captura de destaque.</span></div><h3>Guia visual em destaque</h3><p>Resuma o resultado que o usuário alcançará.</p></article><article class="guide-card"><span class="guide-card__number">2</span><div class="screen-placeholder screen-placeholder--compact"><strong>Imagem do guia</strong><span>Insira uma captura de destaque.</span></div><h3>Procedimento recomendado</h3><p>Apresente uma rotina importante do sistema.</p></article><article class="guide-card"><span class="guide-card__number">3</span><div class="screen-placeholder screen-placeholder--compact"><strong>Imagem do guia</strong><span>Insira uma captura de destaque.</span></div><h3>Relatório mais acessado</h3><p>Mostre como transformar dados em decisão.</p></article></div></section>
<section class="doc-section"><div class="content-grid content-grid--2"><article class="rule-card"><h2>Artigos recentes</h2><div class="resource-list"><div class="resource-item"><strong>Nome do artigo publicado</strong><span>Atualizado recentemente</span></div><div class="resource-item"><strong>Outro conteúdo importante</strong><span>Categoria do artigo</span></div><div class="resource-item"><strong>Boas práticas para usuários</strong><span>Tempo de leitura</span></div></div></article><article class="rule-card"><h2>Perguntas frequentes</h2><div class="faq-list"><article class="faq-item"><h3>Como encontro uma funcionalidade?</h3><p>Oriente o uso da busca e das categorias.</p></article><article class="faq-item"><h3>Onde solicito ajuda?</h3><p>Indique os canais disponíveis.</p></article></div></article></div></section>
$html$, 5, TRUE, 'migration', 'migration'),

  ('10000000-0000-0000-0000-000000000010', 'CATEGORIA_ARTIGOS', 'Índice de categoria',
   'Organiza artigos por assunto com filtros, metadados, conteúdos populares e tutoriais.', $html$
<section class="doc-intro"><span class="doc-kicker">Módulo ou categoria</span><h2>[Nome da categoria]</h2><p>Explique quais temas e atividades o usuário encontrará nesta seção.</p></section>
<div class="filter-chips"><p><span class="filter-chip filter-chip--active">Todos</span><span class="filter-chip">Assunto 1</span><span class="filter-chip">Assunto 2</span><span class="filter-chip">Importação e exportação</span><span class="filter-chip">Permissões</span></p></div>
<section class="doc-section"><h2>Guias disponíveis</h2><div class="resource-list resource-list--large"><article class="resource-item"><span class="number-badge">1</span><span><strong>Como realizar a atividade principal</strong><small>Explique o objetivo deste artigo em uma frase.</small></span><span class="resource-item__meta">6 min · atualizado recentemente</span></article><article class="resource-item"><span class="number-badge">2</span><span><strong>Como configurar uma opção</strong><small>Apresente o resultado esperado do guia.</small></span><span class="resource-item__meta">7 min · guia visual</span></article><article class="resource-item"><span class="number-badge">3</span><span><strong>Importação de informações</strong><small>Oriente sobre formatos, regras e validações.</small></span><span class="resource-item__meta">9 min · passo a passo</span></article><article class="resource-item"><span class="number-badge">4</span><span><strong>Exportação de informações</strong><small>Mostre como gerar e utilizar o arquivo.</small></span><span class="resource-item__meta">6 min · referência</span></article></div></section>
<section class="doc-section"><div class="content-grid content-grid--2"><article class="rule-card"><h2>Artigos populares</h2><ol class="rank-list"><li>Conteúdo mais acessado da categoria</li><li>Dúvida recorrente dos usuários</li><li>Boas práticas recomendadas</li><li>Solução para um erro conhecido</li></ol></article><article class="rule-card"><h2>Tutoriais relacionados</h2><div class="content-grid content-grid--2"><article class="topic-card"><span class="topic-card__icon">▶</span><h3>Tutorial visual</h3><p>Inclua duração e benefício.</p></article><article class="topic-card"><span class="topic-card__icon">▶</span><h3>Demonstração prática</h3><p>Explique o que será demonstrado.</p></article></div></article></div></section>
$html$, 65, TRUE, 'migration', 'migration'),

  ('10000000-0000-0000-0000-000000000011', 'PRIMEIROS_PASSOS', 'Primeiros passos',
   'Jornada inicial com etapas, tutoriais, checklist de implantação e materiais complementares.', $html$
<section class="doc-intro"><span class="doc-kicker">Boas-vindas</span><h2>Primeiros passos no [produto]</h2><p>Apresente a jornada inicial para que o usuário comece com confiança.</p></section>
<section class="doc-section"><h2>Jornada inicial</h2><div class="journey-grid"><article class="journey-card"><span class="journey-card__number">1</span><h3>Acesso ao sistema</h3><p>Explique como entrar e navegar pela primeira vez.</p></article><article class="journey-card"><span class="journey-card__number">2</span><h3>Segurança inicial</h3><p>Oriente senha, autenticação e proteção da conta.</p></article><article class="journey-card"><span class="journey-card__number">3</span><h3>Configurar perfil</h3><p>Mostre preferências e informações pessoais.</p></article><article class="journey-card"><span class="journey-card__number">4</span><h3>Criar primeiro cadastro</h3><p>Ajude o usuário a registrar a primeira informação.</p></article><article class="journey-card"><span class="journey-card__number">5</span><h3>Consultar resultados</h3><p>Apresente consultas e relatórios essenciais.</p></article></div></section>
<section class="doc-section"><h2>Tutoriais visuais</h2><div class="screen-grid"><article class="guide-card"><div class="screen-placeholder screen-placeholder--compact"><strong>Imagem do tutorial</strong><span>Insira a captura da etapa.</span></div><h3>Como acessar o sistema</h3><p>Informe duração e aprendizado.</p></article><article class="guide-card"><div class="screen-placeholder screen-placeholder--compact"><strong>Imagem do tutorial</strong><span>Insira a captura da etapa.</span></div><h3>Configurando seu perfil</h3><p>Mostre o resultado do tutorial.</p></article><article class="guide-card"><div class="screen-placeholder screen-placeholder--compact"><strong>Imagem do tutorial</strong><span>Insira a captura da etapa.</span></div><h3>Visão geral de relatórios</h3><p>Apresente os principais indicadores.</p></article></div></section>
<section class="doc-section"><div class="content-grid content-grid--2"><article class="rule-card"><h2>Checklist de implantação</h2><ul class="status-list"><li class="status-item status-item--done"><span>Acessar com usuário administrador</span><strong>Concluído</strong></li><li class="status-item status-item--done"><span>Configurar perfil e preferências</span><strong>Concluído</strong></li><li class="status-item status-item--progress"><span>Criar primeiro cadastro</span><strong>Em andamento</strong></li><li class="status-item"><span>Consultar ou gerar um relatório</span><strong>Pendente</strong></li></ul></article><article class="rule-card"><h2>Materiais complementares</h2><div class="content-grid content-grid--3"><article class="topic-card"><span class="topic-card__icon">?</span><h3>FAQ</h3><p>Dúvidas comuns.</p></article><article class="topic-card"><span class="topic-card__icon">▶</span><h3>Vídeos</h3><p>Tutoriais rápidos.</p></article><article class="topic-card"><span class="topic-card__icon">A–Z</span><h3>Glossário</h3><p>Termos do sistema.</p></article></div></article></div></section>
$html$, 68, TRUE, 'migration', 'migration'),

  ('10000000-0000-0000-0000-000000000012', 'RELATORIO', 'Guia de relatório',
   'Documenta filtros, período, agrupamento, gráfico, tabela, exportação e boas práticas.', $html$
<section class="doc-intro"><span class="doc-kicker">Relatórios e indicadores</span><h2>Como gerar o relatório de [assunto]</h2><p>Explique como analisar dados, acompanhar indicadores e apoiar decisões.</p></section>
<div class="objective-card"><p><strong>Objetivo de negócio</strong></p><p>Descreva quais decisões este relatório apoia e quais resultados devem ser acompanhados.</p></div>
<section class="doc-section"><h2>Visão do relatório</h2><figure class="screen-frame"><div class="screen-placeholder"><strong>Insira a captura completa do relatório</strong><span>Mostre filtros, gráfico, tabela e ação de exportação.</span></div><figcaption>Visão geral do relatório e seus principais componentes.</figcaption></figure></section>
<section class="doc-section"><h2>Elementos da tela</h2><div class="annotation-grid"><article class="annotation-card"><h3>Filtros</h3><p>Liste os critérios e a forma como são combinados.</p></article><article class="annotation-card"><h3>Período</h3><p>Explique datas disponíveis e valores padrão.</p></article><article class="annotation-card"><h3>Agrupamento</h3><p>Descreva dia, semana, mês ou outra dimensão.</p></article><article class="annotation-card"><h3>Gráfico</h3><p>Oriente a leitura das séries e indicadores.</p></article><article class="annotation-card"><h3>Tabela</h3><p>Explique colunas, totais e detalhamento.</p></article><article class="annotation-card"><h3>Exportação</h3><p>Informe formatos e cuidados com os dados.</p></article></div></section>
<section class="doc-section"><div class="content-grid content-grid--2"><article class="rule-card"><h2>Regras de negócio</h2><ul class="checklist"><li>Explique como filtros são aplicados.</li><li>Informe as permissões necessárias.</li><li>Registre limites de período ou volume.</li></ul></article><article class="rule-card"><h2>Boas práticas</h2><div class="content-grid content-grid--2"><article class="topic-card"><h3>Defina o objetivo</h3><p>Saiba o que precisa analisar.</p></article><article class="topic-card"><h3>Compare períodos</h3><p>Identifique padrões e tendências.</p></article><article class="topic-card"><h3>Use filtros com critério</h3><p>Reduza ruído nos resultados.</p></article><article class="topic-card"><h3>Exporte e compartilhe</h3><p>Apoie decisões em equipe.</p></article></div></article></div></section>
<div class="related-links"><p><strong>Guias relacionados</strong><span>Personalizar colunas</span><span>Agendar relatório</span><span>Exportar dados</span></p></div>
$html$, 45, TRUE, 'migration', 'migration')
ON CONFLICT (codigo) DO UPDATE SET
  nome = EXCLUDED.nome,
  descricao = EXCLUDED.descricao,
  conteudo_html = EXCLUDED.conteudo_html,
  ordem = EXCLUDED.ordem,
  ativo = TRUE,
  updated_at = now(),
  updated_by = 'migration';
